eval "$(/opt/homebrew/bin/brew shellenv)"

for file in ~/.{exports,aliases}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# Load extra (private) settings
[ -f ~/.zshlocal ] && source ~/.zshlocal