# Oh My Zsh
# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Format of command execution time stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="dd.mm.yyyy"

# Plugins (see ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(extract git-extras)
source $ZSH/oh-my-zsh.sh

# Locale
export LC_ALL=en_US.UTF-8
export LANG="en_US"

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Enable zsh-syntax-highlighting
[ -f /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ] && source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Terminal title
DISABLE_AUTO_TITLE="true"
function _set_terminal_title() {
	local title="$(basename "$PWD")"
	if [[ -n $SSH_CONNECTION ]]; then
		title="$title \xE2\x80\x94 $HOSTNAME"
	fi
	echo -ne "\033];$title\007"
}
precmd_functions+=(_set_terminal_title)

# Disable bundle for git-friendly
export GIT_FRIENDLY_NO_BUNDLE=true

# Enable composer install
export GIT_FRIENDLY_NO_COMPOSER=false

# Enable yarn install
export GIT_FRIENDLY_NO_YARN=false

# Disable sharing history between terminals enabled by Oh My Zsh
unsetopt share_history

# Load extra (private) settings
[ -f ~/.zshlocal ] && source ~/.zshlocal
